name: ecluse

packages:
  - packages/**

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  analyze:
    description: Analyse statique de tous les packages
    run: melos exec -- dart analyze --fatal-infos
  test:
    description: Lance les tests de tous les packages
    run: melos exec --dir-exists=test -- dart test
  format:
    description: Vérifie le formatage
    run: melos exec -- dart format --set-exit-if-changed .
