/// Liste de prénoms français courants, utilisée par [NameDetector].
///
/// ATTENTION : liste heuristique de démonstration (v0), voir le README du
/// package. Elle n'a aucune prétention d'exhaustivité ni de qualité
/// statistique — c'est un indice parmi d'autres, pas une vérité INSEE.
/// Comparaisons insensibles à la casse (voir [frenchFirstNames], déjà en
/// minuscules).
///
/// Remplacée en phase 2 par un modèle NER local (voir ROADMAP.md).
const Set<String> frenchFirstNames = <String>{
  // Prénoms féminins classiques et courants
  'aaliyah', 'ada', 'adele', 'adeline', 'adrienne', 'agathe', 'agnes',
  'aimee', 'alice', 'alicia', 'alienor', 'aline', 'alix', 'alizee',
  'amandine', 'ambre', 'amelie', 'amelia', 'amina', 'anaelle', 'anais',
  'anastasia', 'andrea', 'angele', 'angelina', 'angelique', 'anna',
  'annabelle', 'anne', 'annick', 'annie', 'antoinette', 'apolline',
  'ariane', 'arlette', 'assia', 'astrid', 'aude', 'audrey', 'aurelie',
  'aurore', 'axelle', 'aya', 'barbara', 'beatrice', 'benedicte',
  'berenice', 'bernadette', 'bertille', 'blanche', 'brigitte', 'camille',
  'capucine', 'carine', 'carmen', 'caroline', 'cassandre', 'catherine',
  'cecile', 'celeste', 'celine', 'chantal', 'charlene', 'charlotte',
  'chiara', 'chloe', 'christelle', 'christiane', 'christine', 'claire',
  'clara', 'clarisse', 'claude', 'claudette', 'claudine', 'clemence',
  'clementine', 'coline', 'colette', 'constance', 'coralie', 'corinne',
  'cyrielle', 'daniele', 'daphne', 'delphine', 'denise', 'diane',
  'dominique', 'dorothee', 'edith', 'eleonore', 'elisabeth', 'elise',
  'eliane', 'elodie', 'eloise', 'elsa', 'emeline', 'emilie', 'emma',
  'emmanuelle', 'estelle', 'esther', 'eugenie', 'eva', 'evelyne',
  'fabienne', 'fanny', 'fatima', 'fatoumata', 'flavie', 'fleur',
  'florence', 'florentine', 'florianne', 'francoise', 'frida', 'gabrielle',
  'genevieve', 'georgette', 'germaine', 'gilberte', 'gisele', 'giulia',
  'gwendoline', 'helene', 'henriette', 'hortense', 'ines', 'inga',
  'iris', 'irene', 'isabelle', 'jacqueline', 'jade', 'janine', 'jeanne',
  'jeannine', 'jessica', 'jocelyne', 'joelle', 'josephine', 'josette',
  'judith', 'julia', 'julie', 'juliette', 'justine', 'karine', 'katia',
  'laetitia', 'laura', 'laure', 'laurence', 'laurette', 'lea', 'leila',
  'lena', 'leonie', 'liliane', 'lilou', 'lily', 'lina', 'lisa', 'lise',
  'lola', 'lorraine', 'loubna', 'louise', 'louna', 'lucie', 'lucienne',
  'lucile', 'ludivine', 'lydie', 'lyna', 'madeleine', 'maelle', 'maeva',
  'maggie', 'maite', 'malika', 'manon', 'marceline', 'margaux',
  'marguerite', 'margot', 'maria', 'marianne', 'marie', 'marielle',
  'marina', 'marine', 'marion', 'marlene', 'marthe', 'martine', 'mathilde',
  'maude', 'maureen', 'maryse', 'melanie', 'melina', 'melissa', 'meriem',
  'micheline', 'michele', 'mila', 'mireille', 'monique', 'morgane',
  'muriel', 'myriam', 'nadege', 'nadia', 'nadine', 'nathalie', 'nelly',
  'nicole', 'nina', 'ninon', 'noemie', 'nora', 'odette', 'odile',
  'olivia', 'ombeline', 'ophelie', 'oriane', 'pascale', 'patricia',
  'paule', 'paulette', 'pauline', 'perrine', 'philippine', 'priscille',
  'raymonde', 'rebecca', 'regine', 'renee', 'rita', 'roberte', 'romane',
  'rosalie', 'rose', 'roselyne', 'rosine', 'sabine', 'sabrina', 'salome',
  'samia', 'sandra', 'sandrine', 'sarah', 'segolene', 'severine',
  'sidonie', 'simone', 'sixtine', 'sofia', 'solange', 'soline', 'sonia',
  'sophie', 'stella', 'stephanie', 'suzanne', 'suzette', 'sylvette',
  'sylvia', 'sylvie', 'tatiana', 'therese', 'tiphaine', 'valentine',
  'valerie', 'vanessa', 'veronique', 'victoire', 'violette', 'virginie',
  'viviane', 'wendy', 'xaviere', 'yasmine', 'yolande', 'yvette', 'yvonne',
  'zoe', 'zohra',

  // Prénoms masculins classiques et courants
  'abdel', 'abdelkader', 'adam', 'adrien', 'ahmed', 'alain', 'alan',
  'albert', 'alexandre', 'alexis', 'alfred', 'ali', 'alphonse', 'amaury',
  'ambroise', 'amine', 'anatole', 'andre', 'anthony', 'antoine', 'archibald',
  'armand', 'arnaud', 'arsene', 'arthur', 'auguste', 'augustin', 'aurele',
  'aurelien', 'axel', 'aymeric', 'baptiste', 'barnabe', 'bastien',
  'benjamin', 'benoit', 'bernard', 'bertrand', 'bilal', 'boris', 'brice',
  'bruno', 'calixte', 'carl', 'cedric', 'celestin', 'charles',
  'christian', 'christophe', 'clement', 'come', 'constantin',
  'corentin', 'cyprien', 'cyril', 'cyrille', 'damien', 'daniel', 'david',
  'denis', 'didier', 'dimitri', 'donatien', 'edgar', 'edmond',
  'edouard', 'elie', 'elliot', 'emile', 'emmanuel', 'enguerrand', 'enzo',
  'eric', 'ernest', 'esteban', 'etienne', 'eugene', 'evariste', 'fabien',
  'fabrice', 'felicien', 'felix', 'ferdinand', 'fernand', 'florent',
  'florian', 'francis', 'francois', 'frank', 'frederic', 'gabin',
  'gabriel', 'gael', 'gaetan', 'gaspard', 'gaston', 'gauthier', 'gautier',
  'georges', 'gerald', 'gerard', 'germain', 'gilbert', 'gilles', 'grégoire',
  'gregoire', 'guillaume', 'gustave', 'guy', 'hadrien', 'hamid', 'henri',
  'herve', 'hippolyte', 'honore', 'hubert', 'hugo', 'hugues', 'ibrahim',
  'ignace', 'igor', 'isaac', 'ismael', 'ivan', 'jacques', 'jason', 'jean',
  'jeremie', 'jeremy', 'jerome', 'joachim', 'joel', 'johan', 'jonas',
  'jonathan', 'jordan', 'joseph', 'josselin', 'jules', 'julien', 'karim',
  'kevin', 'kylian', 'lambert', 'laurent', 'leo', 'leon', 'leonard',
  'leopold', 'liam', 'lionel', 'loic', 'louis', 'loup', 'luc', 'lucas',
  'lucien', 'ludovic', 'malo', 'mamadou', 'marc', 'marceau', 'marcel',
  'martin', 'mathias', 'mathieu', 'mathis', 'matteo', 'matthieu',
  'maurice', 'maxence', 'maxime', 'maximilien', 'mehdi', 'michel',
  'mohamed', 'moise', 'morgan', 'nathan', 'nathanael', 'nicolas', 'noe',
  'noel', 'octave', 'olivier', 'omar', 'oscar', 'pascal', 'patrice',
  'patrick', 'paul', 'philippe', 'pierre', 'quentin', 'rafael', 'raoul',
  'raphael', 'raymond', 'regis', 'remi', 'rene', 'reynald', 'richard',
  'robert', 'roger', 'roland', 'romain', 'romeo', 'ronan',
  'salim', 'samir', 'samuel', 'sacha', 'sebastien', 'serge', 'simon',
  'stanislas', 'stephane', 'sylvain', 'tanguy', 'theo', 'theodore',
  'thibault', 'thibaut', 'thierry', 'thomas', 'tim', 'timothee', 'tom',
  'tristan', 'ulysse', 'valentin', 'victor', 'vincent', 'vivien',
  'wilfried', 'william', 'xavier', 'yacine', 'yanis', 'yann', 'yannick',
  'youssef', 'yves', 'yvon', 'zacharie',
};
